apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-elastic
  labels:
    app: {{ .Release.Name }}
    component: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: elasticsearch
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.17.24
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: discovery.type
          value: "single-node"
        ports:
        - containerPort: 9200
        - containerPort: 9300
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-elastic-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-elastic
  labels:
    app: {{ .Release.Name }}
    component: elasticsearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: http
  - port: 9300
    targetPort: 9300
    protocol: TCP
    name: transport
  selector:
    app: {{ .Release.Name }}
    component: elasticsearch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-elastic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
