{{- if and .Values.networkPolicies.enabled (eq .Values.networkPolicies.type "native") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-traffic
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-proxy-access
spec:
  podSelector:
    matchLabels:
      app: {{ template "nomad.name" . }}
  ingress:
  - ports:
    - port: {{ .Values.global.proxy.http.port | default 80 }}
    from:
    - ipBlock:
        cidr: {{ .Values.networkPolicies.proxy.cidr }}
  egress:
  - ports:
    - port: {{ .Values.global.proxy.http.port | default 80 }}
    to:
    - ipBlock:
        cidr: {{ .Values.networkPolicies.proxy.cidr }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-rabbitmq-access
spec:
  podSelector:
    matchLabels:
      app: {{ template "nomad.name" . }}
      component: rabbitmq
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "nomad.name" . }}
          component: worker
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
{{- end }}
