{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-namespace-traffic
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    - podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    - podSelector: {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-rabbitmq-access
spec:
  podSelector:
    matchLabels:
      app: {{ template "nomad.name" . }}
      component: rabbitmq
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "nomad.name" . }}
          component: worker
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system

---
{{- if .Values.global.proxy.http.host }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-proxy-access
spec:
  podSelector:
    matchLabels:
      app: {{ template "nomad.name" . }}
      component: proxy
  ingress:
  - ports:
    - port: {{ .Values.global.proxy.http.port | default 80 }}
    from:
    - ipBlock:
        cidr: {{ .Values.networkPolicies.proxy.cidr | default "0.0.0.0/0" }}
  egress:
  - ports:
    - port: {{ .Values.global.proxy.http.port | default 80 }}
    to:
    - ipBlock:
        cidr: {{ .Values.networkPolicies.proxy.cidr | default "0.0.0.0/0" }}
{{- end }}

{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kube-api-access
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 443
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
{{- end }}
{{- end }}
