apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomad-north
  labels:
    app: nomad
    component: north
spec:
  replicas: {{ .Values.north.replicaCount }}
  selector:
    matchLabels:
      app: nomad
      component: north
  template:
    metadata:
      labels:
        app: nomad
        component: north
    spec:
      containers:
      - name: north
        image: "{{ .Values.north.image.repository }}:{{ .Values.north.image.tag }}"
        imagePullPolicy: {{ .Values.north.image.pullPolicy }}
        env:
          {{- range $key, $value := .Values.north.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          - name: NOMAD_MONGO_USERNAME
            value: {{ .Values.mongodb.auth.rootUser | quote }}
          - name: NOMAD_MONGO_PASSWORD
            value: {{ .Values.mongodb.auth.rootPassword | quote }}
          {{- if .Values.global.proxy.http.host }}
          - name: HTTP_PROXY
            value: {{ printf "%s://%s:%s" .Values.global.proxy.http.protocol .Values.global.proxy.http.host .Values.global.proxy.http.port | quote }}
          {{- end }}
          {{- if .Values.global.proxy.https.host }}
          - name: HTTPS_PROXY
            value: {{ printf "%s://%s:%s" .Values.global.proxy.https.protocol .Values.global.proxy.https.host .Values.global.proxy.https.port | quote }}
          {{- end }}
          - name: NO_PROXY
            value: {{ .Values.global.proxy.no_proxy | quote }}
        resources:
          {{- toYaml .Values.north.resources | nindent 10 }}
        volumeMounts:
          - name: shared-volume
            mountPath: /app/.volumes/fs
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: nomad-fs-pvc
