apiVersion: v2
name: nomad
description: A Helm chart to deploy NOMAD in Kubernetes
version: 0.2.19
appVersion: "1.0"
dependencies:
  - name: rabbitmq
    version: 15.2.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: rabbitmq.enabled
  - name: mongodb
    version: 16.4.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled
  - name: jupyterhub
    version: 3.0.3
    repository: https://jupyterhub.github.io/helm-chart
    condition: jupyterhub.enabled
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
