apiVersion: v2
name: nomad
description: A Helm chart to deploy NOMAD in Kubernetes
version: 0.1.8
appVersion: "1.0"
dependencies:
  - name: rabbitmq
    version: 12.10.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: mongodb
    version: 13.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: jupyterhub
    version: 3.0.3
    repository: https://jupyterhub.github.io/helm-chart
    condition: jupyterhub.enabled
